<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.vXtfl5N' shared service.

return $this->privates['.service_locator.vXtfl5N'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('projectMaster' => function (): \App\Entity\ProjectMaster {
    return ($this->privates['.errored..service_locator.vXtfl5N.App\Entity\ProjectMaster'] ?? $this->load('getProjectMasterService.php'));
}));
